---
title: "小破图攻略"
output: html_document
date: "2024-09-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(radiant)
library(rvest)
```

# 1 角色
##  1.1 角色类型

```{r}
df_name_list <- data.frame()

## 天级
url <- "https://wiki.biligame.com/jiangnan/%E5%88%86%E7%B1%BB:%E5%A4%A9%E7%BA%A7%E8%A7%92%E8%89%B2"
page <- read_html(url)

name_list <- page %>% 
  html_nodes(".mw-category-group") %>% 
  html_text() %>% 
  str_split("\\n")

name_list_total <- c()

for(i in 1:length(name_list)){
  # print(name_list[[i]])
  for (j in 1:length(name_list[[i]])){
     name <- name_list[[i]][j] 
     # print(name)
    if(!name %>% str_detect("[A-Z]+") ){
      name_list_total <- c(name_list_total,name)
    }
  }
}
df_name_list <- rbind (df_name_list, data.frame(name = name_list_total, user_cat = "天级角色"))

## 侯级
url <- "https://wiki.biligame.com/jiangnan/%E5%88%86%E7%B1%BB:%E4%BE%AF%E7%BA%A7%E8%A7%92%E8%89%B2"
page <- read_html(url)

name_list <- page %>% 
  html_nodes(".mw-category-group") %>% 
  html_text() %>% 
  str_split("\\n")

name_list_total <- c()

for(i in 1:length(name_list)){
  # print(name_list[[i]])
  for (j in 1:length(name_list[[i]])){
     name <- name_list[[i]][j] 
     # print(name)
    if(!name %>% str_detect("[A-Z]+") ){
      name_list_total <- c(name_list_total,name)
    }
  }
}
df_name_list <- rbind (df_name_list, data.frame(name = name_list_total, user_cat = "侯级角色"))  

## 卿级
url <- "https://wiki.biligame.com/jiangnan/%E5%88%86%E7%B1%BB:%E5%8D%BF%E7%BA%A7%E8%A7%92%E8%89%B2"
page <- read_html(url)

name_list <- page %>% 
  html_nodes(".mw-category-group") %>% 
  html_text() %>% 
  str_split("\\n")

name_list_total <- c()

for(i in 1:length(name_list)){
  # print(name_list[[i]])
  for (j in 1:length(name_list[[i]])){
     name <- name_list[[i]][j] 
     # print(name)
    if(!name %>% str_detect("[A-Z]+") ){
      name_list_total <- c(name_list_total,name)
    }
  }
}
df_name_list <- rbind (df_name_list, data.frame(name = name_list_total, user_cat = "卿级角色"))   

## 士级
url <- "https://wiki.biligame.com/jiangnan/%E5%88%86%E7%B1%BB:%E5%A3%AB%E7%BA%A7%E8%A7%92%E8%89%B2"
page <- read_html(url)

name_list <- page %>% 
  html_nodes(".mw-content-ltr") %>% 
  html_text() %>% 
  str_remove_all("[A-Z]+") %>% 
  str_split("\\n") %>% 
  .[[2]]

name_list <- name_list[!name_list == ""]

name_list_total <- c()

for(i in 1:length(name_list)){
  for (j in 1:length(name_list[[i]])){
     name <- name_list[[i]][j] 
    if(!name %>% str_detect("[A-Z]+") ){
      name_list_total <- c(name_list_total,name)
    }
  }
}
df_name_list <- rbind (df_name_list, data.frame(name = name_list_total, user_cat = "士级角色"))     

df_name_list <- df_name_list %>% 
  unique()

rm(name_list_total)

rm(collection_info)
rm(href_info)
rm(i)
rm(j)
rm(name)
rm(name_list)
rm(url)
rm(page)
```



## 1.2 爬虫
```{r}
url <- "https://wiki.biligame.com/jiangnan/%E8%A7%92%E8%89%B2%E5%9B%BE%E9%89%B4"
page <- read_html(url)

collection_info <- page %>%
  html_nodes("[data-collection]") %>%
  html_attr("data-collection")

href_info <- page %>%
  html_nodes(".text-center a") %>%
  html_attr("href") %>% 
  unique()

df <- data.frame(collection_info,href_info) %>% 
  mutate(url = paste0('https://wiki.biligame.com',href_info))

head(df)
```


```{r}
df_user_info = data.frame()
df_user_property = data.frame()
df_user_network = data.frame()

for (i in 1:nrow(df)) { 
  
  random_sleep <- runif(n=1, min=1, max=5)
  Sys.sleep(random_sleep)
  
  ## url
  url <- df$url[i]
  page <- read_html(url)
  print(url)
  
  mw_headline_info <- page %>%
  html_nodes(".mw-headline") %>%
    html_text()
  
  if (!TRUE %in% str_detect(mw_headline_info,"删除")) {
  
    ## 用户名称
    firstHeading <- page %>%
      html_nodes("[id='firstHeading']") %>%
      html_text()
    user_info = data.frame(firstHeading = firstHeading )  
    print(firstHeading)
    
    # ## 用户类型 天级/侯级
    # user_info$user_cat <- page %>%
    #   html_nodes("a[href='/jiangnan/%E5%88%86%E7%B1%BB:%E5%A4%A9%E7%BA%A7%E8%A7%92%E8%89%B2']") %>%
    #   html_text()
    
    ## 表格信息 包括属性 + 书籍
    property <- page %>%
      html_nodes(".col-xs-12.col-sm-8.col-md-4.col-lg-4") %>%
      html_text() %>% 
      .[1]
    property <- property %>% str_split('升阶') %>% 
      .[[1]] %>% 
      .[2] %>% 
      str_split('\\n') %>% 
      .[[1]] 
    property <- property[!property ==''] 
  
    ## 书籍
    books <- str_trim(property[length(property)])
    user_info$books = books
    
    ## 用户属性
    user_property <- data.frame(firstHeading = firstHeading,
                   property_type = property[c(1,5,9,13,17)],
                   property_degree = property[c(2,6,10,14,18)],
                   property_value_i = property[c(3,7,11,15,19)],
                   property_value_f_total = property[c(4,8,12,16,20)] 
    ) 
    user_property[c('property_value_f_formula','property_value_f')] = str_split_fixed(user_property$property_value_f_total,"=",2)
    df_user_property <- rbind(df_user_property, user_property)
    
    ## 天赋 + 简介
    node_info <- page %>%
    html_nodes(".col-xs-12.col-sm-8.col-md-8.col-lg-8") %>%
    html_text()
    tianfu_list <- node_info[1] %>% 
      str_split('\\n') %>% 
      .[[1]]
    tianfu_list <- tianfu_list[!tianfu_list == ""]
    user_info$tianfu = tianfu_list[1] %>% str_split("展/折") %>% .[[1]] %>% .[1] %>% str_split("：") %>% .[[1]] %>% .[2]
    user_info$tianfu_2star = tianfu_list[2]
    user_info$tianfu_4star = tianfu_list[3]
    user_info$description <- node_info[2]
    
    ## 用户一句话描述
    user_desc <- page %>%
      html_nodes("[style*='padding: 15px;font-size: x-large;text-align: center;word-break: keep-all;font-family:宋体']") %>%
      html_text()
    user_desc <- str_trim(user_desc)
    user_info$user_desc = user_desc
  
    ## 用户关系网
    node_info <- page %>%
    html_nodes(".text-left") %>%
      html_text()
    
    user_network <- data.frame(
      firstHeading = firstHeading,
      friend = node_info[str_detect(node_info,"对『")])
    
    user_network[c('friend_1','friend')] = str_split_fixed(user_network$friend,"对『",2)
    user_network[c('friend','friend_1')] = str_split_fixed(user_network$friend,"』",2)
    user_network[c('friend_1','wording')] = str_split_fixed(user_network$friend_1,"「",2)
    user_network[c('wording','wording_1')] = str_split_fixed(user_network$wording,"」",2)
    
    user_network <- user_network %>% select(-friend_1, -wording_1) %>% 
      filter(!is.na(friend)) %>% 
      filter(!friend == "")
    df_user_network <- rbind(df_user_network, user_network)
    
    df_user_info = rbind(df_user_info, user_info)
  }
  else next 
}

rm(books)
rm(collection_info)
rm(href_info)
rm(i)
rm(mw_headline_info)
rm(node_info)
rm(property)
rm(random_sleep)
rm(tianfu_list)
rm(url)
rm(user_desc)
```

```{r}
df_user_info <- df_user_info %>% left_join(df_name_list, by = c('firstHeading' = 'name'))
df_user_property 
df_user_network 
```


## 存入数据
```{r}
df_user_info %>% write.csv("df_user_info.csv", row.names = F)
df_user_property %>% write.csv("df_user_property.csv", row.names = F)
df_user_network %>% write.csv("df_user_network.csv", row.names = F)
```





# 2.珍宝


## 珍宝类型
```{r}
df_zhenbao_list <- data.frame()

## 天级
url <- "https://wiki.biligame.com/jiangnan/%E5%88%86%E7%B1%BB:%E5%A4%A9%E7%BA%A7%E7%8F%8D%E5%AE%9D"
page <- read_html(url)

name_list <- page %>% 
  html_nodes(".mw-category-group") %>% 
  html_text() %>% 
  str_split("\\n")

zhenbao_list_total_tian <- c()

for(i in 1:length(name_list)){
  # print(name_list[[i]])
  for (j in 1:length(name_list[[i]])){
     name <- name_list[[i]][j] 
     # print(name)
    if(!name %>% str_detect("[A-Z]+") ){
      zhenbao_list_total_tian <- c(zhenbao_list_total_tian,name)
    }
  }
}
df_zhenbao_list <- rbind (df_zhenbao_list, data.frame(name = zhenbao_list_total_tian, cat = "天级珍宝"))   


## 侯级
url <- "https://wiki.biligame.com/jiangnan/%E5%88%86%E7%B1%BB:%E4%BE%AF%E7%BA%A7%E7%8F%8D%E5%AE%9D"
page <- read_html(url)

name_list <- page %>% 
  html_nodes(".mw-content-ltr") %>% 
  html_text() %>% 
  str_remove_all("[A-Z]+") %>% 
  str_split("\\n") %>% 
  .[[2]]

name_list <- name_list[!name_list == ""]

zhenbao_list_total <- c()

for(i in 1:length(name_list)){
  # print(name_list[[i]])
  for (j in 1:length(name_list[[i]])){
     name <- name_list[[i]][j] 
     # print(name)
    if(!name %>% str_detect("[A-Z]+") ){
      zhenbao_list_total <- c(zhenbao_list_total,name)
    }
  }
}
df_zhenbao_list <- rbind (df_zhenbao_list, data.frame(name = zhenbao_list_total, cat = "侯级珍宝"))   

## 卿级
url <- "https://wiki.biligame.com/jiangnan/%E5%88%86%E7%B1%BB:%E5%8D%BF%E7%BA%A7%E7%8F%8D%E5%AE%9D"
page <- read_html(url)

name_list <- page %>% 
  html_nodes(".mw-category-group") %>% 
  html_text() %>% 
  str_split("\\n")

zhenbao_list_total <- c()

for(i in 1:length(name_list)){
  # print(name_list[[i]])
  for (j in 1:length(name_list[[i]])){
     name <- name_list[[i]][j] 
     # print(name)
    if(!name %>% str_detect("[A-Z]+") ){
      zhenbao_list_total <- c(zhenbao_list_total,name)
    }
  }
}
df_zhenbao_list <- rbind (df_zhenbao_list, data.frame(name = zhenbao_list_total, cat = "卿级珍宝"))   

## 专属
url <- "https://wiki.biligame.com/jiangnan/%E5%88%86%E7%B1%BB:%E4%B8%93%E5%B1%9E%E7%8F%8D%E5%AE%9D"
page <- read_html(url)

name_list <- page %>% 
  html_nodes(".mw-category-group") %>% 
  html_text() %>% 
  str_split("\\n")

zhenbao_list_total <- c()

for(i in 1:length(name_list)){
  # print(name_list[[i]])
  for (j in 1:length(name_list[[i]])){
     name <- name_list[[i]][j] 
     # print(name)
    if(!name %>% str_detect("[A-Z]+") ){
      zhenbao_list_total <- c(zhenbao_list_total,name)
    }
  }
}
df_zhenbao_list <- rbind (df_zhenbao_list, data.frame(name = zhenbao_list_total, cat = "专属珍宝"))   

df_zhenbao_list <- df_zhenbao_list %>% 
  unique()
rm(zhenbao_list_total_tian)
rm(zhenbao_list_total)

rm(books)
rm(collection_info)
rm(href_info)
rm(i)
rm(mw_headline_info)
rm(node_info)
rm(property)
rm(random_sleep)
rm(tianfu_list)
rm(url)
rm(user_desc)
```




## 珍宝爬虫

```{r}

url <- "https://wiki.biligame.com/jiangnan/%E7%8F%8D%E5%AE%9D%E5%9B%BE%E9%89%B4"
page <- read_html(url)

collection_info <- page %>%
  html_nodes("[data-collection]") %>%
  html_attr("data-collection")

href_info <- page %>%
  html_nodes(".text-center a") %>%
  html_attr("href") %>% 
  unique()

df <- data.frame(collection_info,href_info) %>% 
  mutate(url = paste0('https://wiki.biligame.com',href_info))

df
```



```{r}
df_zhenbao_info = data.frame()
df_zhenbao_property = data.frame()
df_zhenbao_tianfu = data.frame()

for (i in 1:nrow(df)) { 
  
  random_sleep <- runif(n=1, min=1, max=5)
  Sys.sleep(random_sleep)
  
  ## url
  url <- df$url[i]
  page <- read_html(url)
  print(url)
  
  mw_headline_info <- page %>%
  html_nodes(".mw-headline") %>%
    html_text()
  
  if (!TRUE %in% str_detect(mw_headline_info,"删除")) {
  
    ## 用户名称
    firstHeading <- page %>%
      html_nodes("[id='firstHeading']") %>%
      html_text()
    zhenbao_info = data.frame(firstHeading = firstHeading )  
    print(firstHeading)

    ## 表格信息 包括属性 
    property_list <- page %>%
    html_nodes(".col-xs-12.col-sm-8.col-md-4.col-lg-4") %>%
    html_text() %>% 
    .[1] %>% 
      str_split('五十') %>% 
      .[[1]] %>% 
      .[2] %>% 
      str_split('\\n') %>% 
      .[[1]] 
    property <- property_list[2:26]
    zhenbao_property <- as.data.frame(matrix(unlist(property), ncol = 5, byrow = TRUE)) 
    zhenbao_property$firstHeading <- firstHeading
    df_zhenbao_property <- rbind(df_zhenbao_property, zhenbao_property)
  
    ## 专珍归属人物
    property_user <- property_list[!property_list == '']
    user_name <- str_trim(property_user[length(property_user)] %>% str_split('.png') %>% .[[1]] %>% .[2])
    zhenbao_info$user_name <- user_name
    
    ## 天赋 + 简介
    node_info <- page %>%
      html_nodes(".col-xs-12.col-sm-8.col-md-8.col-lg-8") %>%
      html_text() %>% 
      str_trim()
    node_info
    lvl_str <- str_split(node_info, '\\n') %>% .[[1]] %>% .[1] 
    lvl_str <- substr(lvl_str,3,nchar(lvl_str))
    lvl_str <- lvl_str %>% str_split(pattern = "\\+") %>% .[[1]] 
    lvl_str <- lvl_str[!lvl_str == '']
    lvl_str <- c( c("初始") , lvl_str)
    node_info <- str_split(node_info, '\\n') %>% .[[1]] %>% .[length(.)]
    node_info
    tianfu <- substr(node_info, 1,5) 
    node_info <- str_split(node_info,pattern = tianfu)[[1]]
    node_info
    node_info <- node_info[!node_info == '']
    node_info
    node_info <- data.frame(node_info)
    node_info
    node_info[c('tianfu_property','zhuangbei_property')] = str_split_fixed(node_info$node_info,paste0(user_name,"装备时"),2)
    node_info
    node_info$zhenbao_name = firstHeading
    node_info
    node_info$tianfu = tianfu
    node_info
    node_info$zhenbao_lvl = lvl_str
    node_info
    df_zhenbao_tianfu <- rbind(df_zhenbao_tianfu,node_info)
    
    ## 描述
    zhenbao_desc <- page %>%
      html_nodes("[style*='text-align: left;padding:10px']") %>%
      html_text()
    zhenbao_desc <- str_trim(zhenbao_desc)
    zhenbao_info$zhenbao_desc = zhenbao_desc
    df_zhenbao_info <- rbind(df_zhenbao_info, zhenbao_info)
  }
  else next 
}

rm(books)
rm(collection_info)
rm(href_info)
rm(i)
rm(mw_headline_info)
rm(node_info)
rm(property)
rm(random_sleep)
rm(tianfu_list)
rm(url)
rm(user_desc)
```
```{r}
df_zhenbao_info <- df_zhenbao_info  %>% left_join(df_zhenbao_list, by = c( 'firstHeading' = 'name'))
df_zhenbao_property 
df_zhenbao_tianfu 
```
## 存入数据
```{r}
df_zhenbao_info %>% write.csv("df_zhenbao_info.csv",row.names = F)
df_zhenbao_property %>% write.csv("df_zhenbao_property.csv",row.names = F)
df_zhenbao_tianfu %>% write.csv("df_zhenbao_tianfu.csv",row.names = F)
```





```{r}
# https://www.taptap.cn/moment/470232763660763863
# https://docs.qq.com/sheet/DWnB6RGZBSmVkVWVQ?tab=ss_gww2lc&viewId=v5HdWy
```



# 3.别人的搭配

```{r}

```

